import type { TranslationKeys } from "../translations";

export const engTranslations: TranslationKeys = {
  court_name: "In the Court of",
  location: "Location",
  case_number: "Case Number",
  case_type: "Case Type",
  petitioner: "Petitioner",
  respondent: "Respondent",
  versus: "Versus",
  procedural_history: "Procedural History",
  arguments: "Arguments",
  reasoning: "Reasoning / Analysis",
  final_order: "Final Order",
  date: "Date",
  place: "Place",
  judge: "Judge",
  designation: "Designation",
  advocate_petitioner: "Advocate for Petitioner",
  advocate_respondent: "Advocate for Respondent",
  operative_order: "Operative Order",
  directions: "Specific Directions",
  reset_form: "Reset Form",
  save_pdf: "Print / Save PDF",
  generating: "Generating...",
  order_title: "Court Order",
  filling_order: "Filling Order...",
  full_name_address: "Full Name and Address",
  additional_text: "Additional Details / Arguments",
  signature_placeholder: "(Signature)",
  add_point: "+ Add Reasoning Point",
  add_direction: "+ Add Direction",
  final_order_header: ":: FINAL ORDER ::",
  transcript_title: "Transcript",
  copy_transcript: "Copy Transcript",
  download_pdf: "Download as PDF",
  clear_transcript: "Clear Transcript",
  clear_confirm: "Are you sure you want to clear the transcript?",
  filing_date: "Filing Date",
  registration_date: "Registration Date",
  decision_date: "Decision Date",

  complainant: "Complainant",
  accused: "Accused",
  other_parties: "Other Parties",

  government_advocate: "Government Advocate",
  other_advocate: "Other Advocate",

  appearance_mode: "Appearance Mode",

  case_details: "Case Details",
  acts_sections: "Acts / Sections",
  case_category: "Case Category",
  police_station: "Police Station",
  property_details: "Property / Seized Items",
  other_details: "Other Details",

  issues_framed: "Issues Framed",
  evidence: "Evidence",
  oral_evidence: "Oral Evidence",
  documentary_evidence: "Documentary Evidence",

  final_outcome: "Final Outcome",

  listening: "Listening...",
  add_point_audio: "Add Point via Audio",
  add_direction_audio: "Add Direction via Audio",
};
