import type { TranslationKeys } from "../translations";

export const gujTranslations: TranslationKeys = {
  court_name: "કોર્ટનું નામ",
  location: "સ્થળ",
  case_number: "કેસ નંબર",
  case_type: "કેસનો પ્રકાર",
  petitioner: "અરજદાર/વાદી",
  respondent: "પ્રતિવાદી",
  versus: "વિરુદ્ધ",
  procedural_history: "કેસની હકીકત",
  arguments: "દલીલો",
  reasoning: "મુદ્દાઓ/વિશ્લેષણ",
  final_order: "અંતિમ આદેશ",
  date: "તારીખ",
  place: "સ્થળ",
  judge: "જજ સાહેબ",
  designation: "હોદ્દો",
  advocate_petitioner: "વાદી તરફે વકીલ",
  advocate_respondent: "પ્રતિવાદી તરફે વકીલ",
  operative_order: "હુકમની વિગત",
  directions: "વિશ્લેષણ સૂચનાઓ",
  reset_form: "ફોર્મ સાફ કરો",
  save_pdf: "પ્રિન્ટ /પીડીએફ સેવ કરો",
  generating: "સેવ થઈ રહ્યું છે...",
  order_title: "કોર્ટ હુકમ",
  filling_order: "હુકમ ભરાઈ રહ્યો છે...",
  full_name_address: "સંપૂર્ણ નામ અને સરનામું",
  additional_text: "અન્ય વિગતો / રજૂઆતો",
  signature_placeholder: "(સહી)",
  add_point: "+ મુદ્દો ઉમેરો",
  add_direction: "+ સૂચના ઉમેરો",
  final_order_header: ":: આખરી હુકમ ::",
  transcript_title: "ટ્રાન્સક્રિપ્ટ",
  copy_transcript: "ટ્રાન્સક્રિપ્ટ કોપી કરો",
  download_pdf: "પીડીએફ ડાઉનલોડ કરો",
  clear_transcript: "ટ્રાન્સક્રિપ્ટ સાફ કરો",
  clear_confirm: "શું તમે ખરેખર ટ્રાન્સક્રિપ્ટ સાફ કરવા માંગો છો?",
  filing_date: "ફાઇલિંગ તારીખ",
  registration_date: "નોંધણી તારીખ",
  decision_date: "ફૈસલાની તારીખ",

  complainant: "ફરિયાદી",
  accused: "આરોપી",
  other_parties: "અન્ય પક્ષો",

  government_advocate: "સરકારી વકીલ",
  other_advocate: "અન્ય વકીલ",

  appearance_mode: "હાજરીનો પ્રકાર",

  case_details: "કેસની વિગતો",
  acts_sections: "ધારા / કલમો",
  case_category: "કેસની શ્રેણી",
  police_station: "પોલીસ સ્ટેશન",
  property_details: "જપ્ત માલમસાલા / સંપત્તિ",
  other_details: "અન્ય વિગતો",

  issues_framed: "નક્કી કરાયેલા મુદ્દાઓ",
  evidence: "પુરાવા",
  oral_evidence: "મૌખિક પુરાવા",
  documentary_evidence: "દસ્તાવેજી પુરાવા",

  final_outcome: "અંતિમ પરિણામ",

  listening: "સાંભળવામાં આવી રહ્યું છે...",
  add_point_audio: "આવાજથી મુદ્દો ઉમેરો",
  add_direction_audio: "આવાજથી સૂચના ઉમેરો",
};
