import type { TranslationKeys } from "../translations";

export const hinTranslations: TranslationKeys = {
  court_name: "न्यायालय",
  location: "स्थान",
  case_number: "मामला संख्या",
  case_type: "मामले का प्रकार",
  petitioner: "याचिकाकर्ता",
  respondent: "प्रतिवादी",
  versus: "बनाम",
  procedural_history: "प्रक्रियात्मक इतिहास",
  arguments: "तर्क",
  reasoning: "तर्क / विश्लेषण",
  final_order: "अंतिम आदेश",
  date: "तारीख",
  place: "स्थान",
  judge: "न्यायाधीश",
  designation: "पद",
  advocate_petitioner: "याचिकाकर्ता के अधिवक्ता",
  advocate_respondent: "प्रतिवादी के अधिवक्ता",
  operative_order: "प्रभावी आदेश",
  directions: "विशिष्ट निर्देश",
  reset_form: "फॉर्म रिसेट करें",
  save_pdf: "प्रिंट / पीडीएफ सहेजें",
  generating: "सहेज रहा है...",
  order_title: "न्यायालय आदेश",
  filling_order: "आदेश भरा जा रहा है...",
  full_name_address: "पूरा नाम और पता",
  additional_text: "अतिरिक्त विवरण / तर्क",
  signature_placeholder: "(हस्ताक्षर)",
  add_point: "+ तर्क बिंदु जोड़ें",
  add_direction: "+ दिशा-निर्देश जोड़ें",
  final_order_header: ":: अंतिम आदेश ::",
  transcript_title: "प्रतिलिपि",
  copy_transcript: "प्रतिलिपि कॉपी करें",
  download_pdf: "पीडीएफ के रूप में डाउनलोड करें",
  clear_transcript: "प्रतिलिपि साफ़ करें",
  clear_confirm: "क्या आप वाकई प्रतिलिपि साफ़ करना चाहते हैं?",
  filing_date: "दाखिल करने की तारीख",
  registration_date: "पंजीकरण तिथि",
  decision_date: "निर्णय की तिथि",

  complainant: "शिकायतकर्ता",
  accused: "आरोपी",
  other_parties: "अन्य पक्ष",

  government_advocate: "सरकारी वकील",
  other_advocate: "अन्य वकील",

  appearance_mode: "उपस्थिति का प्रकार",

  case_details: "मामले का विवरण",
  acts_sections: "धाराएं / अधिनियम",
  case_category: "मामले की श्रेणी",
  police_station: "थाना",
  property_details: "जब्त संपत्ति / सामग्री",
  other_details: "अन्य विवरण",

  issues_framed: "निर्धारित मुद्दे",
  evidence: "साक्ष्य",
  oral_evidence: "मौखिक साक्ष्य",
  documentary_evidence: "दस्तावेजी साक्ष्य",

  final_outcome: "अंतिम परिणाम",

  listening: "सुन रहे हैं...",
  add_point_audio: "आवाज़ से बिंदु जोड़ें",
  add_direction_audio: "आवाज़ से निर्देश जोड़ें",
};
