sonar.projectKey=web_node_courtmitra_4735c974-db64-4f21-a946-62ad0ffdb3ab
sonar.qualitygate.wait=true
sonar.sources=src
sonar.tests=src/tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/tests/**,node_modules/**,dist/**

